<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TransactionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('transactions')->delete();
        
        DB::table('transactions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cash',
                'tanggal' => '2022-07-04',
                'nominal' => 500000.0,
                'pajak' => 50000.0,
                'income' => 400000.0,
                'bukti' => NULL,
                'keterangan' => 'Pemasukan Bulan Juni',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cash',
                'tanggal' => '2022-07-31',
                'nominal' => 1000000.0,
                'pajak' => 100000.0,
                'income' => 800000.0,
                'bukti' => NULL,
                'keterangan' => 'Pemasukan Bulan Juli',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'jenis' => 'Pengeluaran',
                'sumber' => 'Belanja',
                'tanggal' => '2022-07-02',
                'nominal' => 450000.0,
                'pajak' => NULL,
                'income' => NULL,
                'bukti' => NULL,
                'keterangan' => 'Belanja ABC',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'jenis' => 'pos',
                'sumber' => 'Operasi',
                'tanggal' => '2022-07-07',
                'nominal' => 100000.0,
                'pajak' => NULL,
                'income' => NULL,
                'bukti' => NULL,
                'keterangan' => 'Tambal Ban Angkot',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cashless',
                'tanggal' => '2022-07-06',
                'nominal' => 100000.0,
                'pajak' => NULL,
                'income' => NULL,
                'bukti' => NULL,
                'keterangan' => 'Yayyy',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cash',
                'tanggal' => '2022-06-30',
                'nominal' => 1000000.0,
                'pajak' => 100000.0,
                'income' => 800000.0,
                'bukti' => NULL,
                'keterangan' => 'Uwooow',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'jenis' => 'Pengeluaran',
                'sumber' => 'Operasi',
                'tanggal' => '2022-07-07',
                'nominal' => 400000.0,
                'pajak' => NULL,
                'income' => NULL,
                'bukti' => NULL,
                'keterangan' => 'Gaada keterangan',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'jenis' => 'Pengeluaran',
                'sumber' => 'Operasi',
                'tanggal' => '2022-08-01',
                'nominal' => 720000.0,
                'pajak' => NULL,
                'income' => NULL,
                'bukti' => NULL,
                'keterangan' => 'Ini keterangan',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cash',
                'tanggal' => '2022-01-01',
                'nominal' => 400000.0,
                'pajak' => 40000.0,
                'income' => 320000.0,
                'bukti' => NULL,
                'keterangan' => '1 Januari',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cash',
                'tanggal' => '2022-01-12',
                'nominal' => 1000000.0,
                'pajak' => 100000.0,
                'income' => 800000.0,
                'bukti' => NULL,
                'keterangan' => 'Pemasukan januari',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cash',
                'tanggal' => '2022-02-16',
                'nominal' => 1000000.0,
                'pajak' => 100000.0,
                'income' => 800000.0,
                'bukti' => NULL,
                'keterangan' => 'Pemasukan Februari',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cash',
                'tanggal' => '2022-03-16',
                'nominal' => 1000000.0,
                'pajak' => 100000.0,
                'income' => 800000.0,
                'bukti' => NULL,
                'keterangan' => 'Pemasukan Maret',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cash',
                'tanggal' => '2022-04-16',
                'nominal' => 1000000.0,
                'pajak' => 100000.0,
                'income' => 800000.0,
                'bukti' => NULL,
                'keterangan' => 'Pemasukan April',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cash',
                'tanggal' => '2022-05-16',
                'nominal' => 1000000.0,
                'pajak' => 100000.0,
                'income' => 800000.0,
                'bukti' => NULL,
                'keterangan' => 'Pemasukan Mei',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cash',
                'tanggal' => '2022-06-16',
                'nominal' => 1000000.0,
                'pajak' => 100000.0,
                'income' => 800000.0,
                'bukti' => NULL,
                'keterangan' => 'Pemasukan Juni',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cash',
                'tanggal' => '2022-07-16',
                'nominal' => 1000000.0,
                'pajak' => 100000.0,
                'income' => 800000.0,
                'bukti' => NULL,
                'keterangan' => 'Pemasukan Juli',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 22,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cash',
                'tanggal' => '2021-12-29',
                'nominal' => 1000000.0,
                'pajak' => 100000.0,
                'income' => 800000.0,
                'bukti' => NULL,
                'keterangan' => 'Pemasukan Desember 2021',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 24,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cash',
                'tanggal' => '2022-07-27',
                'nominal' => 128000.0,
                'pajak' => 12800.0,
                'income' => 115200.0,
                'bukti' => NULL,
                'keterangan' => 'Pemasukan transaksi kafe tanggal: 2022-07-27',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 25,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cash',
                'tanggal' => '2022-07-27',
                'nominal' => 69963969.0,
                'pajak' => 6996396.9,
                'income' => 62967572.1,
                'bukti' => NULL,
                'keterangan' => 'Pemasukan transaksi kafe tanggal: 2022-07-27',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 26,
                'jenis' => 'Pengeluaran',
                'sumber' => 'Dicololong maling',
                'tanggal' => '2022-08-02',
                'nominal' => 69000.0,
                'pajak' => NULL,
                'income' => NULL,
                'bukti' => 'kuGambar/tNLA54MnvKuXGPLoU9Nhe9JxEd9reNYjjA2SEHtv.jpg',
                'keterangan' => 'MALINGGGGG',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 27,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cash',
                'tanggal' => '2022-08-02',
                'nominal' => 800000000.0,
                'pajak' => 80000000.0,
                'income' => 720000000.0,
                'bukti' => 'kuGambar/SYYZaStew51vxnp6PN2XISxnIdjl8CROXTJIJP77.png',
                'keterangan' => 'Give away Mr.Beast',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 28,
                'jenis' => 'Pengeluaran',
                'sumber' => 'Mr.Beast Scam',
                'tanggal' => '2022-08-02',
                'nominal' => 1000000.0,
                'pajak' => NULL,
                'income' => NULL,
                'bukti' => 'kuGambar/KWxqG2W6rRzPE4np89QbWxxh0Y6nfkVg8nSGmVjc.png',
                'keterangan' => 'Ternyata bukan Mr.Beast, tapi MR.BEST',
                'status' => 'waiting',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 29,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cash',
                'tanggal' => '2022-08-05',
                'nominal' => 12312.0,
                'pajak' => 1231.2,
                'income' => 11080.8,
                'bukti' => 'kuGambar/wzTJL2TpsW2Sq8nHMXEsTBAhnqRKRlvVwlyRWriJ.jpg',
                'keterangan' => 'awwa',
                'status' => 'waiting',
                'created_at' => '2022-08-05 13:01:04',
                'updated_at' => '2022-08-05 13:01:04',
            ),
            23 => 
            array (
                'id' => 30,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cash',
                'tanggal' => '2022-08-05',
                'nominal' => 6434252.0,
                'pajak' => 643425.2,
                'income' => 5790826.8,
                'bukti' => 'kuGambar/rpdAG4XXUYYq8FtmxFJJlgfD3T6FKprypcZ0pkHb.jpg',
                'keterangan' => 'Awawwaaw',
                'status' => 'waiting',
                'created_at' => '2022-08-05 13:01:23',
                'updated_at' => '2022-08-05 13:01:23',
            ),
            24 => 
            array (
                'id' => 31,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cash',
                'tanggal' => '2022-08-07',
                'nominal' => 209159907.0,
                'pajak' => 20915990.7,
                'income' => 188243916.3,
                'bukti' => NULL,
                'keterangan' => 'Pemasukan transaksi kafe tanggal: 2022-08-07',
                'status' => 'waiting',
                'created_at' => '2022-08-07 16:38:11',
                'updated_at' => '2022-08-07 16:38:11',
            ),
            25 => 
            array (
                'id' => 32,
                'jenis' => 'Pemasukan',
                'sumber' => 'Cashless',
                'tanggal' => '2022-08-09',
                'nominal' => 209120907.0,
                'pajak' => 20912090.7,
                'income' => 188208816.3,
                'bukti' => NULL,
                'keterangan' => 'Pemasukan transaksi kafe tanggal: 2022-08-09',
                'status' => 'waiting',
                'created_at' => '2022-08-09 12:12:07',
                'updated_at' => '2022-08-09 12:12:07',
            ),
            26 => 
            array (
                'id' => 33,
                'jenis' => 'Pemasukan',
                'sumber' => 'Pendapatan layanan',
                'tanggal' => '2022-08-21',
                'nominal' => 200000.0,
                'pajak' => 20000.0,
                'income' => 180000.0,
                'bukti' => NULL,
                'keterangan' => 'Tes',
                'status' => 'waiting',
                'created_at' => '2022-08-21 13:14:23',
                'updated_at' => '2022-08-21 13:14:23',
            ),
            27 => 
            array (
                'id' => 34,
                'jenis' => 'Pemasukan',
                'sumber' => 'Pendapatan layanan',
                'tanggal' => '2022-08-21',
                'nominal' => 360000.0,
                'pajak' => 36000.0,
                'income' => 324000.0,
                'bukti' => NULL,
                'keterangan' => 'Tes tes',
                'status' => 'waiting',
                'created_at' => '2022-08-21 13:23:39',
                'updated_at' => '2022-08-21 13:23:39',
            ),
            28 => 
            array (
                'id' => 39,
                'jenis' => 'Pemasukan',
            'sumber' => 'Pendapatan layanan (Revenue)',
                'tanggal' => '2022-08-22',
                'nominal' => 750000.0,
                'pajak' => 75000.0,
                'income' => 675000.0,
                'bukti' => 'kuGambar/wR0dp6hxBLBsIqeIQkyEQVO7jfAGrgiyYv6vk8gq.jpg',
                'keterangan' => 'Tes jurnal transaksi revenue',
                'status' => 'waiting',
                'created_at' => '2022-08-21 14:46:58',
                'updated_at' => '2022-08-21 14:46:58',
            ),
            29 => 
            array (
                'id' => 40,
                'jenis' => 'Pengeluaran',
                'sumber' => 'Gaji karyawan',
                'tanggal' => '2022-08-01',
                'nominal' => 8000000.0,
                'pajak' => NULL,
                'income' => NULL,
                'bukti' => 'kuGambar/AMU2V7Dh0JdMs9C1QLbq3uEm0sLK4oXixujsm8ke.jpg',
                'keterangan' => 'Gaji karyawan bulan Juli',
                'status' => 'waiting',
                'created_at' => '2022-08-21 15:16:42',
                'updated_at' => '2022-08-21 15:16:42',
            ),
            30 => 
            array (
                'id' => 41,
                'jenis' => 'Pemasukan',
            'sumber' => 'Pendapatan layanan (Revenue)',
                'tanggal' => '2022-08-21',
                'nominal' => 300000.0,
                'pajak' => 30000.0,
                'income' => 270000.0,
                'bukti' => NULL,
                'keterangan' => 'Revenue',
                'status' => 'waiting',
                'created_at' => '2022-08-21 15:41:38',
                'updated_at' => '2022-08-21 15:41:38',
            ),
            31 => 
            array (
                'id' => 42,
                'jenis' => 'Pengeluaran',
                'sumber' => 'Gaji karyawan',
                'tanggal' => '2022-08-21',
                'nominal' => 8000000.0,
                'pajak' => NULL,
                'income' => NULL,
                'bukti' => NULL,
                'keterangan' => 'Gaji',
                'status' => 'waiting',
                'created_at' => '2022-08-21 15:43:26',
                'updated_at' => '2022-08-21 15:43:26',
            ),
            32 => 
            array (
                'id' => 43,
                'jenis' => 'Pemasukan',
            'sumber' => 'Pendapatan layanan (Revenue)',
                'tanggal' => '2022-08-21',
                'nominal' => 22000000.0,
                'pajak' => 2200000.0,
                'income' => 19800000.0,
                'bukti' => NULL,
                'keterangan' => 'fasda',
                'status' => 'waiting',
                'created_at' => '2022-08-21 15:44:38',
                'updated_at' => '2022-08-21 15:44:38',
            ),
        ));
        
        
    }
}